name: QA Automation Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pytest
          pip install requests
          pip install python-dotenv

      - name: Run tests
        env:
          BASE_URL: https://www.saucedemo.com/
          STANDARD_USER: standard_user
          STANDARD_PASSWORD: secret_sauce
        run: pytest test_api_users.py test_login.py::test_valid_login test_inventory.py::test_inventory_items_display -v